<?php
/**
 * PostHog Purchase Event
 *
 * @var \KingfisherDirect\Posthog\Block\PurchaseEvent $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$orderData = $block->getOrderData();
if (!empty($orderData)) {
    $orderJson = json_encode($orderData, JSON_HEX_TAG | JSON_HEX_AMP);
}
?>
<?php if (!empty($orderData) && $orderJson !== false): ?>
<?php
$scriptString = <<<SCRIPT
if (typeof posthog !== 'undefined') { posthog.capture("purchase", {$orderJson}); }
SCRIPT;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif ?>
