<?php
/**
 * PostHog Purchase Event
 *
 * @var \KingfisherDirect\Posthog\Block\PurchaseEvent $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$orderData = $block->getOrderData();
?>
<?php if (!empty($orderData)): ?>
<?php
$orderJson = json_encode($orderData, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
$scriptString = <<<SCRIPT
    if (typeof posthog !== "undefined") {
        posthog.capture("purchase", {$orderJson});
    }
    SCRIPT;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif ?>
